import { useEffect, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Grid, LinearProgress, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import EventNoteRounded from "@mui/icons-material/EventNoteRounded";
import MeetingRoomRounded from "@mui/icons-material/MeetingRoomRounded";
import HourglassTopRounded from "@mui/icons-material/HourglassTopRounded";
import SmsFailedRounded from "@mui/icons-material/SmsFailedRounded";
import AddRounded from "@mui/icons-material/AddRounded";
import OpenInNewRounded from "@mui/icons-material/OpenInNewRounded";
import { useParams } from "react-router-dom";
import { api, patchJSON, postJSON } from "../api";
import type { ReferenceData, Visit } from "../types";
import { MetricCard, PageHeader } from "../components/AdminUI";
import { StatusChip } from "../components/StatusChip";

export function AdminPage({ fixedSection }: { fixedSection?: string }) {
  const { section: routeSection } = useParams(); const section = fixedSection ?? routeSection ?? "dashboard"; const [error, setError] = useState("");
  return <Box sx={{ p: { xs: 2, md: 3 }, maxWidth: 1500, mx: "auto" }}>{error && <Alert severity="error" onClose={() => setError("")} sx={{ mb: 2 }}>{error}</Alert>}{section === "dashboard" && <Dashboard setError={setError} />}{section === "visits" && <VisitAdmin setError={setError} />}{section === "resources" && <Resources setError={setError} />}{section === "statistics" && <Statistics setError={setError} />}{section === "audit" && <Audit setError={setError} />}{section === "api" && <APIPage />}</Box>;
}

function Dashboard({ setError }: { setError: (v: string) => void }) {
  const [counts, setCounts] = useState<Record<string, number>>({}); useEffect(() => { api<{ counts: Record<string, number> }>("/api/v1/admin/dashboard").then((x) => setCounts(x.counts)).catch((e) => setError(e.message)); }, [setError]);
  return <><PageHeader eyebrow="OPERATIONS" title="관리 Dashboard" description="실시간 방문·승인·알림·보안 운영 상태를 요약합니다." /><Grid container spacing={2}>{[["오늘 방문자", counts.today ?? 0, "개별 방문자 기준", <EventNoteRounded />, "#3978A8"], ["현재 체류", counts.current ?? 0, "재난 대응 기준 인원", <MeetingRoomRounded />, "#176B5B"], ["승인 대기", counts.pendingApproval ?? 0, "Workflow 조치 필요", <HourglassTopRounded />, "#D58A20"], ["알림 실패", counts.failedMessages ?? 0, "최대 5회 자동 재시도", <SmsFailedRounded />, "#C94C53"]].map(([label, value, helper, icon, tone]) => <Grid key={String(label)} size={{ xs: 6, lg: 3 }}><MetricCard label={String(label)} value={Number(value)} helper={String(helper)} icon={icon} tone={String(tone)} /></Grid>)}</Grid><Grid container spacing={2} mt={.2}><Grid size={{ xs: 12, md: 7 }}><Card><CardContent><Typography variant="h6">운영 준비도</Typography><Typography variant="body2" color="text.secondary" mb={3}>관리자 설정에서 회사 정책과 연동을 활성화할 수 있습니다.</Typography>{[["승인 대기 해소", counts.pendingApproval ?? 0], ["알림 실패 처리", counts.failedMessages ?? 0], ["Watch List 활성", counts.watchlist ?? 0]].map(([label, value], i) => <Box key={String(label)} mb={2}><Stack direction="row" justifyContent="space-between"><Typography variant="body2">{label}</Typography><Typography variant="body2" fontWeight={800}>{Number(value)}건</Typography></Stack><LinearProgress variant="determinate" value={Math.max(8, 100 - Number(value) * 8)} color={i === 1 ? "error" : "primary"} sx={{ mt: 1, height: 7, borderRadius: 4 }} /></Box>)}</CardContent></Card></Grid><Grid size={{ xs: 12, md: 5 }}><Card><CardContent><Typography variant="h6">보안 기준</Typography><Stack spacing={1.2} mt={2}>{["QR에는 개인정보 미포함", "랜덤 Token + HMAC 조회", "1회 사용·재발급 즉시 폐기", "개인정보 AES-256-GCM 암호화", "모든 주요 동작 감사 기록"].map((x) => <Stack key={x} direction="row" spacing={1}><Chip label="✓" size="small" color="success" /><Typography variant="body2">{x}</Typography></Stack>)}</Stack></CardContent></Card></Grid></Grid></>;
}

function VisitAdmin({ setError }: { setError: (v: string) => void }) {
  const [items, setItems] = useState<Visit[]>([]); const [visitors, setVisitors] = useState<Record<string, unknown>[]>([]); const [tab, setTab] = useState<"visits" | "visitors" | "watchlist">("visits"); const [watch, setWatch] = useState<Record<string, unknown>[]>([]); const [watchOpen, setWatchOpen] = useState(false); const [watchForm, setWatchForm] = useState({ name: "", phone: "", company: "", reason: "" });
  const load = async () => { try { const [v, people, wl] = await Promise.all([api<{ items: Visit[] }>("/api/v1/visits?limit=200"), api<{ items: Record<string, unknown>[] }>("/api/v1/admin/visitors"), api<{ items: Record<string, unknown>[] }>("/api/v1/admin/watchlist")]); setItems(v.items); setVisitors(people.items); setWatch(wl.items); } catch (e) { setError(e instanceof Error ? e.message : "데이터를 불러오지 못했습니다"); } }; useEffect(() => { void load(); }, []);
  const approval = async (visit: Visit, approve: boolean) => { const reason = prompt(approve ? "승인 메모 (선택)" : "반려 사유") ?? ""; if (!approve && !reason) return; try { await postJSON(`/api/v1/visits/${visit.id}/${approve ? "approve" : "reject"}`, { reason }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "처리하지 못했습니다"); } };
  const addWatch = async () => { try { await postJSON("/api/v1/admin/watchlist", watchForm); setWatchOpen(false); setWatchForm({ name: "", phone: "", company: "", reason: "" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "등록하지 못했습니다"); } };
  return <><PageHeader eyebrow="VISITOR CONTROL" title="방문 · 방문자 관리" description="전체 방문 Workflow, 방문자 이력과 보안 Watch List를 관리합니다." actions={tab === "watchlist" ? <Button variant="contained" startIcon={<AddRounded />} onClick={() => setWatchOpen(true)}>제한 등록</Button> : undefined} /><Stack direction="row" spacing={1} mb={2}>{[["visits", "전체 방문"], ["visitors", "방문자 이력"], ["watchlist", "Watch List"]].map(([value, label]) => <Button key={value} variant={tab === value ? "contained" : "outlined"} onClick={() => setTab(value as typeof tab)}>{label}</Button>)}</Stack><TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow>{tab === "visits" ? <><TableCell>일시 / 번호</TableCell><TableCell>방문자</TableCell><TableCell>담당 / 장소</TableCell><TableCell>상태</TableCell><TableCell align="right">승인</TableCell></> : tab === "visitors" ? <><TableCell>방문자</TableCell><TableCell>전화번호</TableCell><TableCell>회사</TableCell><TableCell>방문 횟수</TableCell><TableCell>최근 방문</TableCell></> : <><TableCell>대상</TableCell><TableCell>회사</TableCell><TableCell>제한 사유</TableCell><TableCell>기간</TableCell><TableCell>상태</TableCell></>}</TableRow></TableHead><TableBody>
      {tab === "visits" && items.map((x) => <TableRow key={x.id}><TableCell><Typography variant="body2" fontWeight={700}>{new Date(x.startAt).toLocaleString("ko-KR")}</Typography><Typography variant="caption" sx={{ fontFamily: "monospace" }}>{x.requestNo}</Typography></TableCell><TableCell>{x.primaryVisitor}{x.visitorCount > 1 ? ` 외 ${x.visitorCount - 1}명` : ""}<Typography variant="caption" display="block" color="text.secondary">{x.company}</Typography></TableCell><TableCell>{x.hostName}<Typography variant="caption" display="block" color="text.secondary">{x.siteName} · {x.lobbyName}</Typography></TableCell><TableCell><StatusChip status={x.status} /></TableCell><TableCell align="right">{x.status === "PENDING_APPROVAL" && <Stack direction="row" justifyContent="flex-end"><Button size="small" color="error" onClick={() => void approval(x, false)}>반려</Button><Button size="small" onClick={() => void approval(x, true)}>승인</Button></Stack>}</TableCell></TableRow>)}
      {tab === "visitors" && visitors.map((x) => <TableRow key={String(x.id)}><TableCell>{String(x.name)}</TableCell><TableCell>{String(x.phone)}</TableCell><TableCell>{String(x.company || "-")}</TableCell><TableCell>{String(x.visitCount)}</TableCell><TableCell>{x.lastVisitAt ? new Date(String(x.lastVisitAt)).toLocaleDateString("ko-KR") : "-"}</TableCell></TableRow>)}
      {tab === "watchlist" && watch.map((x) => <TableRow key={String(x.id)}><TableCell>{String(x.name || "전화번호 기준")}</TableCell><TableCell>{String(x.company || "-")}</TableCell><TableCell>{String(x.reason)}</TableCell><TableCell>{new Date(String(x.startsAt)).toLocaleDateString("ko-KR")} – {x.endsAt ? new Date(String(x.endsAt)).toLocaleDateString("ko-KR") : "영구"}</TableCell><TableCell><Chip size="small" color={x.active ? "error" : "default"} label={x.active ? "활성" : "해제"} /></TableCell></TableRow>)}
    </TableBody></Table></TableContainer><Dialog open={watchOpen} onClose={() => setWatchOpen(false)} fullWidth><DialogTitle>Watch List 등록</DialogTitle><DialogContent><Alert severity="warning" sx={{ mb: 2 }}>제한 정보와 사유는 관리자·보안 담당자에게만 노출됩니다.</Alert><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="이름" value={watchForm.name} onChange={(e) => setWatchForm({ ...watchForm, name: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="전화번호" value={watchForm.phone} onChange={(e) => setWatchForm({ ...watchForm, phone: e.target.value })} /></Grid><Grid size={{ xs: 12 }}><TextField fullWidth label="회사" value={watchForm.company} onChange={(e) => setWatchForm({ ...watchForm, company: e.target.value })} /></Grid><Grid size={{ xs: 12 }}><TextField fullWidth required multiline label="제한 사유" value={watchForm.reason} onChange={(e) => setWatchForm({ ...watchForm, reason: e.target.value })} /></Grid></Grid></DialogContent><DialogActions><Button onClick={() => setWatchOpen(false)}>취소</Button><Button variant="contained" color="error" disabled={!watchForm.reason || (!watchForm.phone && !watchForm.company)} onClick={() => void addWatch()}>제한 등록</Button></DialogActions></Dialog></>;
}

function Resources({ setError }: { setError: (v: string) => void }) {
  const [ref, setRef] = useState<ReferenceData | null>(null); const [users, setUsers] = useState<Record<string, unknown>[]>([]); const [open, setOpen] = useState<"site" | "lobby" | "department" | null>(null); const [form, setForm] = useState<Record<string, string>>({});
  const load = async () => { try { const [r, u] = await Promise.all([api<ReferenceData>("/api/v1/reference-data"), api<{ items: Record<string, unknown>[] }>("/api/v1/admin/users")]); setRef(r); setUsers(u.items); } catch (e) { setError(e instanceof Error ? e.message : "기준정보를 불러오지 못했습니다"); } }; useEffect(() => { void load(); }, []);
  const save = async () => { if (!open) return; try { await postJSON(`/api/v1/admin/${open === "department" ? "organizations" : `${open}s`}`, form); setOpen(null); setForm({}); await load(); } catch (e) { setError(e instanceof Error ? e.message : "저장하지 못했습니다"); } };
  const updateUser = async (id: string, patch: Record<string, unknown>) => { try { await patchJSON(`/api/v1/admin/users/${id}`, patch); await load(); } catch (e) { setError(e instanceof Error ? e.message : "사용자 권한을 변경하지 못했습니다"); } };
  return <><PageHeader eyebrow="MASTER DATA" title="조직 · 사업장 · 권한" description="멀티 사업장과 로비, 조직 및 Keycloak 프로비저닝 사용자를 관리합니다." /><Grid container spacing={2}><Grid size={{ xs: 12, lg: 4 }}><ResourceCard title="사업장" items={ref?.sites ?? []} label={(x) => `${String(x.name)} · ${String(x.address)}`} onAdd={() => { setForm({}); setOpen("site"); }} /></Grid><Grid size={{ xs: 12, lg: 4 }}><ResourceCard title="로비" items={ref?.lobbies ?? []} label={(x) => String(x.name)} onAdd={() => { setForm({ siteId: ref?.sites[0]?.id ?? "" }); setOpen("lobby"); }} /></Grid><Grid size={{ xs: 12, lg: 4 }}><ResourceCard title="조직" items={ref?.departments ?? []} label={(x) => String(x.name)} onAdd={() => { setForm({}); setOpen("department"); }} /></Grid></Grid><Card sx={{ mt: 3 }}><CardContent><Typography variant="h6">사용자 · RBAC</Typography><Typography variant="body2" color="text.secondary" mb={2}>Keycloak 그룹 매핑 후에도 Role과 계정 활성 상태를 즉시 변경할 수 있습니다. 마지막 최고 관리자는 보호됩니다.</Typography><TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>사용자</TableCell><TableCell>아이디</TableCell><TableCell>인증</TableCell><TableCell>Role</TableCell><TableCell>상태</TableCell><TableCell>최근 로그인</TableCell></TableRow></TableHead><TableBody>{users.map((u) => <TableRow key={String(u.id)} sx={{ opacity: u.active === false ? .55 : 1 }}><TableCell>{String(u.displayName)}</TableCell><TableCell>{String(u.username)}</TableCell><TableCell>{String(u.source).toUpperCase()}</TableCell><TableCell><Stack spacing={.5} alignItems="flex-start"><TextField select value={String(u.role)} onChange={(e) => void updateUser(String(u.id), { role: e.target.value })} sx={{ minWidth: 170 }}>{["user", "lobby", "dept_manager", "security", "auditor", "admin", "super_admin"].map((role) => <MenuItem key={role} value={role}>{role}</MenuItem>)}</TextField>{u.source === "oidc" && u.roleOverride === true && <Button size="small" onClick={() => void updateUser(String(u.id), { useOidcMapping: true })}>SSO 그룹 매핑으로 복귀</Button>}</Stack></TableCell><TableCell><Button size="small" color={u.active === false ? "success" : "error"} variant="outlined" onClick={() => void updateUser(String(u.id), { active: u.active === false })}>{u.active === false ? "활성화" : "비활성화"}</Button></TableCell><TableCell>{u.lastLoginAt ? new Date(String(u.lastLoginAt)).toLocaleString("ko-KR") : "-"}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
    <Dialog open={Boolean(open)} onClose={() => setOpen(null)} fullWidth><DialogTitle>{open === "site" ? "사업장" : open === "lobby" ? "로비" : "조직"} 추가</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{open === "lobby" && <TextField select label="사업장" value={form.siteId ?? ""} onChange={(e) => setForm({ ...form, siteId: e.target.value })}>{ref?.sites.map((x) => <MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField>}{open !== "department" && <TextField required label="코드" value={form.code ?? ""} onChange={(e) => setForm({ ...form, code: e.target.value })} />}<TextField required label="이름" value={form.name ?? ""} onChange={(e) => setForm({ ...form, name: e.target.value })} />{open === "site" && <><TextField label="주소" value={form.address ?? ""} onChange={(e) => setForm({ ...form, address: e.target.value })} /><TextField label="지도 URL" value={form.mapUrl ?? ""} onChange={(e) => setForm({ ...form, mapUrl: e.target.value })} /></>}{open === "lobby" && <TextField multiline label="방문 안내" value={form.instructions ?? ""} onChange={(e) => setForm({ ...form, instructions: e.target.value })} />}</Stack></DialogContent><DialogActions><Button onClick={() => setOpen(null)}>취소</Button><Button variant="contained" disabled={!form.name || (open !== "department" && !form.code)} onClick={() => void save()}>저장</Button></DialogActions></Dialog></>;
}
function ResourceCard<T extends { id: string }>({ title, items, label, onAdd }: { title: string; items: T[]; label: (x: T) => string; onAdd: () => void }) { return <Card sx={{ height: "100%" }}><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h6">{title}</Typography><Button size="small" startIcon={<AddRounded />} onClick={onAdd}>추가</Button></Stack><Divider sx={{ my: 2 }} /><Stack spacing={1}>{items.map((x) => <Paper key={x.id} variant="outlined" sx={{ p: 1.5 }}><Typography variant="body2" fontWeight={700}>{label(x)}</Typography></Paper>)}{items.length === 0 && <Typography color="text.secondary">등록 항목 없음</Typography>}</Stack></CardContent></Card>; }

function Statistics({ setError }: { setError: (v: string) => void }) {
  const [data, setData] = useState<{ daily: { date: string; scheduled: number; checkedIn: number }[]; byDepartment: { name: string; count: number }[] }>({ daily: [], byDepartment: [] }); const [notifications, setNotifications] = useState<Record<string, unknown>[]>([]); useEffect(() => { Promise.all([api<typeof data>("/api/v1/admin/statistics?days=30"), api<{ items: Record<string, unknown>[] }>("/api/v1/admin/notifications")]).then(([a, b]) => { setData(a); setNotifications(b.items); }).catch((e) => setError(e.message)); }, [setError]); const max = Math.max(1, ...data.byDepartment.map((x) => x.count));
  return <><PageHeader eyebrow="INSIGHTS" title="통계 · 알림" description="최근 30일 방문량과 부서별 수요, SMS Adapter 발송 상태를 확인합니다." /><Grid container spacing={2}><Grid size={{ xs: 12, lg: 7 }}><Card><CardContent><Typography variant="h6">일별 방문 흐름</Typography><Box sx={{ mt: 3, display: "flex", alignItems: "end", gap: .6, height: 220 }}>{data.daily.map((d) => <Box key={d.date} title={`${d.date}: ${d.checkedIn}/${d.scheduled}`} sx={{ flex: 1, minWidth: 3, height: `${Math.max(3, d.scheduled * 6)}px`, maxHeight: 200, bgcolor: d.checkedIn === d.scheduled ? "primary.main" : "info.main", borderRadius: "4px 4px 0 0" }} />)}</Box><Typography variant="caption" color="text.secondary">막대: 예정 방문자 · 체크인 완료 시 녹색</Typography></CardContent></Card></Grid><Grid size={{ xs: 12, lg: 5 }}><Card><CardContent><Typography variant="h6">부서별 방문량</Typography><Stack spacing={2} mt={2}>{data.byDepartment.slice(0, 8).map((x) => <Box key={x.name}><Stack direction="row" justifyContent="space-between"><Typography variant="body2">{x.name}</Typography><Typography variant="body2" fontWeight={800}>{x.count}</Typography></Stack><LinearProgress variant="determinate" value={x.count / max * 100} sx={{ mt: .7, height: 6, borderRadius: 4 }} /></Box>)}</Stack></CardContent></Card></Grid></Grid><Card sx={{ mt: 3 }}><CardContent><Typography variant="h6">최근 알림 이력</Typography><TableContainer component={Paper} variant="outlined" sx={{ mt: 2 }}><Table size="small"><TableHead><TableRow><TableCell>생성</TableCell><TableCell>수신자</TableCell><TableCell>템플릿</TableCell><TableCell>상태</TableCell><TableCell>시도</TableCell><TableCell>오류</TableCell></TableRow></TableHead><TableBody>{notifications.slice(0, 100).map((n) => <TableRow key={String(n.id)}><TableCell>{new Date(String(n.createdAt)).toLocaleString("ko-KR")}</TableCell><TableCell>{String(n.recipient)}</TableCell><TableCell>{String(n.templateKey)}</TableCell><TableCell><Chip size="small" color={n.status === "failed" ? "error" : n.status === "sent" || n.status === "logged" ? "success" : "default"} label={String(n.status)} /></TableCell><TableCell>{String(n.attempts)}</TableCell><TableCell>{String(n.error || "-")}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card></>;
}

function Audit({ setError }: { setError: (v: string) => void }) {
  const [items, setItems] = useState<Record<string, unknown>[]>([]); useEffect(() => { api<{ items: Record<string, unknown>[] }>("/api/v1/admin/audit-logs?limit=300").then((x) => setItems(x.items)).catch((e) => setError(e.message)); }, [setError]);
  return <><PageHeader eyebrow="IMMUTABLE TRAIL" title="Audit Log" description="로그인, 개인정보 조회, QR 검증과 모든 운영 변경을 추적합니다." /><TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>시간</TableCell><TableCell>행위자</TableCell><TableCell>이벤트</TableCell><TableCell>대상</TableCell><TableCell>IP</TableCell><TableCell>상세</TableCell></TableRow></TableHead><TableBody>{items.map((x) => <TableRow key={String(x.id)}><TableCell sx={{ whiteSpace: "nowrap" }}>{new Date(String(x.createdAt)).toLocaleString("ko-KR")}</TableCell><TableCell>{String(x.actor)}</TableCell><TableCell><Chip size="small" label={String(x.action)} /></TableCell><TableCell>{String(x.resourceType)} · {String(x.resourceId || "-")}</TableCell><TableCell>{String(x.ipAddress)}</TableCell><TableCell><Typography variant="caption" sx={{ fontFamily: "monospace", wordBreak: "break-all" }}>{JSON.stringify(x.details)}</Typography></TableCell></TableRow>)}</TableBody></Table></TableContainer></>;
}

function APIPage() { const tools = ["search_visits", "get_today_visitors", "get_current_visitors", "get_visit", "create_visit", "cancel_visit", "search_visitor_history", "get_lobby_status", "get_visit_statistics"]; return <><PageHeader eyebrow="INTEGRATION" title="API / MCP" description="사내 시스템과 AI Agent가 동일한 RBAC·감사 경계를 사용합니다." actions={<Button variant="outlined" endIcon={<OpenInNewRounded />} href="/api/v1/openapi.json" target="_blank">OpenAPI 3.1</Button>} /><Grid container spacing={2}><Grid size={{ xs: 12, md: 5 }}><Card><CardContent><Typography variant="h6">MCP Streamable HTTP</Typography><Typography color="text.secondary" mt={1}>개인 API 키의 <code>mcp</code> 범위로 연결합니다.</Typography><Paper variant="outlined" sx={{ p: 2, mt: 2, bgcolor: "#10231F", color: "#DDF3EB", fontFamily: "monospace", wordBreak: "break-all" }}>{window.location.origin}/mcp<br /><br />Authorization: Bearer vf_…</Paper><Alert severity="info" sx={{ mt: 2 }}>도구 결과의 방문자 이름과 전화번호는 기본 마스킹되며 사용자·부서·사업장 범위가 자동 적용됩니다.</Alert></CardContent></Card></Grid><Grid size={{ xs: 12, md: 7 }}><Card><CardContent><Typography variant="h6">제공 Tool</Typography><Grid container spacing={1.2} mt={1}>{tools.map((tool) => <Grid key={tool} size={{ xs: 12, sm: 6 }}><Paper variant="outlined" sx={{ p: 1.5 }}><Typography variant="body2" fontWeight={750} sx={{ fontFamily: "monospace" }}>{tool}</Typography></Paper></Grid>)}</Grid></CardContent></Card></Grid></Grid></>; }
