import { useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Grid, InputAdornment, Paper, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import EventAvailableRounded from "@mui/icons-material/EventAvailableRounded";
import MeetingRoomRounded from "@mui/icons-material/MeetingRoomRounded";
import ExitToAppRounded from "@mui/icons-material/ExitToAppRounded";
import PersonOffRounded from "@mui/icons-material/PersonOffRounded";
import QrCodeScannerRounded from "@mui/icons-material/QrCodeScannerRounded";
import PersonAddAltRounded from "@mui/icons-material/PersonAddAltRounded";
import SearchRounded from "@mui/icons-material/SearchRounded";
import { useNavigate } from "react-router-dom";
import { api, postJSON } from "../api";
import type { LobbyVisitor } from "../types";
import { MetricCard, PageHeader } from "../components/AdminUI";
import { StatusChip } from "../components/StatusChip";

export function LobbyPage() {
  const navigate = useNavigate(); const [tab, setTab] = useState<"today" | "current">("today"); const [data, setData] = useState<{ counts: Record<string, number>; items: LobbyVisitor[] }>({ counts: {}, items: [] }); const [error, setError] = useState(""); const [connected, setConnected] = useState(false);
  const [query, setQuery] = useState("");
  const load = useCallback(async () => { try { setData(await api(`/api/v1/lobby/${tab}?q=${encodeURIComponent(query)}`)); } catch (e) { setError(e instanceof Error ? e.message : "로비 현황을 불러오지 못했습니다"); } }, [tab, query]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const stream = new EventSource("/api/v1/lobby/stream"); stream.addEventListener("ready", () => setConnected(true)); stream.addEventListener("visitflow", () => void load()); stream.onerror = () => setConnected(false); return () => stream.close(); }, [load]);
  const checkout = async (id: string) => { try { await postJSON("/api/v1/checkouts", { visitorVisitId: id, method: "lobby" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "퇴실 처리하지 못했습니다"); } };
  return <Box sx={{ p: { xs: 2, md: 3 }, maxWidth: 1500, mx: "auto" }}><PageHeader eyebrow="LIVE LOBBY" title="Lobby Dashboard" description="오늘 방문 예정과 현재 사내 체류 인원을 실시간으로 관리합니다." actions={<><Button startIcon={<PersonAddAltRounded />} onClick={() => navigate("/lobby/walk-in")}>현장 등록</Button><Button variant="contained" startIcon={<QrCodeScannerRounded />} onClick={() => navigate("/lobby/scan")}>QR 스캔</Button></>} />{error && <Alert severity="error" onClose={() => setError("")} sx={{ mb: 2 }}>{error}</Alert>}<Stack direction="row" alignItems="center" spacing={1} mb={2}><Box sx={{ width: 9, height: 9, borderRadius: "50%", bgcolor: connected ? "success.main" : "warning.main" }} /><Typography variant="caption" color="text.secondary">{connected ? "실시간 연결됨" : "재연결 중 · 화면 조회는 정상"}</Typography></Stack>
    <Grid container spacing={2}>{[["방문 예정", data.counts.scheduled ?? 0, "오늘 체크인 대기", <EventAvailableRounded />, "#3978A8"], ["현재 방문중", data.counts.current ?? 0, "재난 시 체류 기준 인원", <MeetingRoomRounded />, "#176B5B"], ["퇴실 완료", data.counts.completed ?? 0, "오늘 퇴실 처리", <ExitToAppRounded />, "#61736E"], ["미방문", data.counts.noShow ?? 0, "정책시간 경과", <PersonOffRounded />, "#D58A20"]].map(([label, value, helper, icon, tone]) => <Grid key={String(label)} size={{ xs: 6, lg: 3 }}><MetricCard label={String(label)} value={Number(value)} helper={String(helper)} icon={icon} tone={String(tone)} /></Grid>)}</Grid>
    <Card sx={{ mt: 3 }}><Tabs value={tab} onChange={(_, value) => setTab(value)} sx={{ px: 2, borderBottom: "1px solid #E1E9E6" }}><Tab value="today" label="오늘 방문자" /><Tab value="current" label={`현재 방문자 ${data.counts.current ?? 0}`} /></Tabs><CardContent><TextField fullWidth value={query} onChange={(e) => setQuery(e.target.value)} placeholder="이름 / 회사 / 담당자 / 부서 / 전화번호 검색" sx={{ mb: 2 }} slotProps={{ input: { startAdornment: <InputAdornment position="start"><SearchRounded /></InputAdornment> } }} /><Stack spacing={1.25}>{data.items.map((item) => <Paper key={item.visitorVisitId} variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ md: "center" }} spacing={2}><Stack direction="row" spacing={2} alignItems="center"><Box sx={{ width: 72, textAlign: "center" }}><Typography fontWeight={850}>{new Date(item.startAt).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}</Typography><Typography variant="caption" color="text.secondary">{item.checkedInAt ? `입실 ${new Date(item.checkedInAt).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}` : "예정"}</Typography></Box><Box><Typography fontWeight={800}>{item.visitor} · {item.company || "회사 미입력"}</Typography><Typography variant="body2" color="text.secondary">{item.host} / {item.department || "부서 미지정"} · {item.site} {item.lobby && `/ ${item.lobby}`}</Typography></Box></Stack><Stack direction="row" spacing={1} alignItems="center"><StatusChip status={item.status} />{item.status === "CHECKED_IN" && <Button color="secondary" variant="outlined" startIcon={<ExitToAppRounded />} onClick={() => void checkout(item.visitorVisitId)}>퇴실</Button>}</Stack></Stack></Paper>)}{data.items.length === 0 && <Box sx={{ py: 8, textAlign: "center" }}><Typography color="text.secondary">표시할 방문자가 없습니다.</Typography></Box>}</Stack></CardContent></Card>
  </Box>;
}
