import { useEffect, useRef, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import VideocamRounded from "@mui/icons-material/VideocamRounded";
import StopCircleOutlined from "@mui/icons-material/StopCircleOutlined";
import QrCodeScannerRounded from "@mui/icons-material/QrCodeScannerRounded";
import CheckCircleRounded from "@mui/icons-material/CheckCircleRounded";
import { api, postJSON } from "../api";
import type { ReferenceData } from "../types";
import { PageHeader } from "../components/AdminUI";

type VerifyResult = { valid: boolean; token: string; visitorVisitId: string; visitId: string; visitor: string; company?: string; host: string; department?: string; site: string; lobby?: string; purpose: string; startAt: string; endAt: string };
type BarcodeDetectorLike = { detect: (source: HTMLVideoElement) => Promise<{ rawValue: string }[]> };

export function ScannerPage() {
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const timerRef = useRef<number | null>(null);
  const [token, setToken] = useState(""); const [scannedValue, setScannedValue] = useState(""); const [result, setResult] = useState<VerifyResult | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [camera, setCamera] = useState(false); const [ref, setRef] = useState<ReferenceData | null>(null); const [lobbyId, setLobbyId] = useState(""); const [badgeNo, setBadgeNo] = useState("");
  useEffect(() => { api<ReferenceData>("/api/v1/reference-data").then((x) => { setRef(x); if (x.lobbies[0]) setLobbyId(x.lobbies[0].id); }); return () => stopCamera(); }, []);
  const verify = async (value = token) => { if (!value.trim() || busy) return; setBusy(true); setError(""); setResult(null); try { const verified = await postJSON<VerifyResult>("/api/v1/qr/verify", { token: value.trim() }); setResult(verified); setScannedValue(value.trim()); stopCamera(); } catch (e) { setError(e instanceof Error ? e.message : "QR을 확인하지 못했습니다"); } finally { setBusy(false); } };
  const startCamera = async () => {
    setError(""); const Detector = (window as unknown as { BarcodeDetector?: new (options: { formats: string[] }) => BarcodeDetectorLike }).BarcodeDetector;
    if (!Detector) { setError("이 브라우저는 카메라 QR 판독 API를 지원하지 않습니다. USB 스캐너 또는 직접 입력을 사용하세요."); return; }
    try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } }, audio: false }); streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } setCamera(true); const detector = new Detector({ formats: ["qr_code"] }); timerRef.current = window.setInterval(async () => { if (!videoRef.current) return; try { const found = await detector.detect(videoRef.current); if (found[0]?.rawValue) { setToken(found[0].rawValue); await verify(found[0].rawValue); } } catch { /* transient camera frame */ } }, 450); } catch (e) { setError(e instanceof Error ? e.message : "카메라를 시작하지 못했습니다"); }
  };
  const stopCamera = () => { if (timerRef.current != null) window.clearInterval(timerRef.current); timerRef.current = null; streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; setCamera(false); };
  const checkin = async () => { if (!result) return; setBusy(true); try { await postJSON("/api/v1/checkins", { token: scannedValue, lobbyId, badgeNo, method: camera ? "camera" : "scanner" }); alert(`${result.visitor} 님 체크인이 완료되었습니다.`); setResult(null); setToken(""); setScannedValue(""); setBadgeNo(""); } catch (e) { setError(e instanceof Error ? e.message : "체크인하지 못했습니다"); } finally { setBusy(false); } };
  return <Box sx={{ p: { xs: 2, md: 3 }, maxWidth: 1100, mx: "auto" }}><PageHeader eyebrow="SECURE ENTRY" title="QR Scan" description="웹 카메라, 모바일 카메라, USB QR 스캐너와 직접 입력을 지원합니다." />{error && <Alert severity="error" onClose={() => setError("")} sx={{ mb: 2 }}>{error}</Alert>}<Grid container spacing={3}><Grid size={{ xs: 12, md: 6 }}><Card><CardContent><Typography variant="h6">스캔 장치</Typography><Typography variant="body2" color="text.secondary" mb={2}>USB 스캐너는 입력창에 포커스를 둔 상태에서 QR을 읽으면 됩니다.</Typography><TextField autoFocus fullWidth multiline minRows={3} label="QR URL 또는 Token" value={token} onChange={(e) => setToken(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void verify(); } }} /><Stack direction="row" spacing={1} mt={2}><Button fullWidth variant="contained" startIcon={busy ? <CircularProgress size={18} /> : <QrCodeScannerRounded />} onClick={() => void verify()} disabled={busy || !token}>QR 확인</Button><Button fullWidth variant="outlined" startIcon={camera ? <StopCircleOutlined /> : <VideocamRounded />} onClick={() => camera ? stopCamera() : void startCamera()}>{camera ? "카메라 중지" : "카메라 시작"}</Button></Stack><Box sx={{ mt: 2, borderRadius: 3, overflow: "hidden", bgcolor: "#10201D", aspectRatio: "4/3", display: camera ? "block" : "none" }}><video ref={videoRef} muted playsInline style={{ width: "100%", height: "100%", objectFit: "cover" }} /></Box><Alert severity="info" sx={{ mt: 2 }}>카메라는 HTTPS 또는 localhost에서만 동작합니다. 인트라넷 운영 시 리버스 프록시에 TLS를 설정하세요.</Alert></CardContent></Card></Grid>
    <Grid size={{ xs: 12, md: 6 }}><Card sx={{ minHeight: 470 }}><CardContent>{!result ? <Box sx={{ minHeight: 410, display: "grid", placeItems: "center", textAlign: "center" }}><Box><QrCodeScannerRounded sx={{ fontSize: 72, color: "#B9C9C4" }} /><Typography variant="h6" mt={2}>방문증을 스캔하세요</Typography><Typography color="text.secondary">검증 결과와 최소 방문자 정보가 여기에 표시됩니다.</Typography></Box></Box> : <Stack spacing={2}><Stack direction="row" alignItems="center" spacing={1}><CheckCircleRounded color="success" sx={{ fontSize: 34 }} /><Box><Typography variant="h5">유효한 방문증</Typography><Typography variant="body2" color="text.secondary">서명·기간·폐기·재사용 검증 완료</Typography></Box></Stack><Paper variant="outlined" sx={{ p: 3, bgcolor: "#F7FAF8" }}><Typography variant="h4">{result.visitor}</Typography><Typography color="text.secondary">{result.company || "회사 미입력"}</Typography><Stack spacing={1.25} mt={3}><Line label="방문일시" value={`${new Date(result.startAt).toLocaleString("ko-KR")} – ${new Date(result.endAt).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}`} /><Line label="담당자" value={`${result.department || "부서 미지정"} · ${result.host}`} /><Line label="방문 장소" value={`${result.site} ${result.lobby ? `· ${result.lobby}` : ""}`} /><Line label="방문 목적" value={result.purpose} /></Stack></Paper><TextField select fullWidth label="처리 로비" value={lobbyId} onChange={(e) => setLobbyId(e.target.value)}>{ref?.lobbies.map((x) => <MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><TextField fullWidth label="임시 출입증 번호 (선택)" value={badgeNo} onChange={(e) => setBadgeNo(e.target.value)} /><Button size="large" variant="contained" color="success" startIcon={<CheckCircleRounded />} disabled={busy} onClick={() => void checkin()}>체크인 완료</Button></Stack>}</CardContent></Card></Grid></Grid>
  </Box>;
}
function Line({ label, value }: { label: string; value: string }) { return <Stack direction="row" spacing={2}><Typography variant="body2" color="text.secondary" sx={{ width: 82, flexShrink: 0 }}>{label}</Typography><Typography variant="body2" fontWeight={700}>{value}</Typography></Stack>; }
