import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Divider, FormControlLabel, Grid, MenuItem, Stack, Switch, Tab, Table, TableBody, TableCell, TableHead, TableRow, Tabs, TextField, Typography } from "@mui/material";
import SaveRounded from "@mui/icons-material/SaveRounded";
import LinkRounded from "@mui/icons-material/LinkRounded";
import CheckCircleRounded from "@mui/icons-material/CheckCircleRounded";
import ContentCopyRounded from "@mui/icons-material/ContentCopyRounded";
import WarningAmberRounded from "@mui/icons-material/WarningAmberRounded";
import { api, postJSON, putJSON } from "../api";
import { PageHeader } from "../components/AdminUI";

type Setting = { key: string; value: string; secret: boolean; configured: boolean };
type Field = { key: string; label: string; help?: string; secret?: boolean; type?: string; multiline?: boolean; options?: [string, string][] };
type TrackingViolation = { origin: string; directive: string; page: string; count: number; lastSeen: string; allowed: boolean };
const fields: Record<string, Field[]> = {
  general: [
    { key: "general.service_name", label: "서비스 이름" }, { key: "general.company_name", label: "회사/조직명" }, { key: "general.base_url", label: "외부 기준 URL", help: "모바일 방문증 및 MMS QR 이미지의 공개 기준 URL. 예: https://visit.company.intra" }, { key: "general.default_locale", label: "기본 언어", help: "ko, en, ja, zh 중 하나. 모바일 방문증과 사전등록 화면의 기본값입니다." }, { key: "general.supported_locales", label: "지원 언어", help: "공백으로 구분. 예: ko en ja" },
  ],
  oidc: [
    { key: "oidc.issuer_url", label: "Keycloak Issuer URL", help: "예: https://keycloak.intra/realms/company" }, { key: "oidc.client_id", label: "Client ID" }, { key: "oidc.client_secret", label: "Client Secret", secret: true }, { key: "oidc.scopes", label: "Scopes" }, { key: "oidc.admin_group", label: "관리자 그룹" }, { key: "oidc.lobby_group", label: "로비 그룹" }, { key: "oidc.security_group", label: "보안 그룹" }, { key: "oidc.auditor_group", label: "감사 그룹" }, { key: "oidc.department_manager_group", label: "부서 관리자 그룹" },
    { key: "mcp.oauth.resource", label: "MCP 리소스 식별자", help: "비우면 외부 기준 URL + /mcp 입니다. 클라이언트가 실제로 접속하는 공개 주소여야 하며 Keycloak Audience 매퍼에 이 값을 적습니다. 예: https://visit.company.intra/mcp" }, { key: "mcp.oauth.audience", label: "허용 대상 (aud · azp)", help: "공백으로 구분한 MCP 클라이언트 ID. Audience 매퍼 없이 쓸 때 토큰의 azp 또는 aud 와 비교합니다. 예: claude-mcp cursor-mcp" }, { key: "mcp.oauth.scopes", label: "SSO 토큰 범위", help: "read write mcp 중 SSO 로 들어온 사용자에게 줄 범위. mcp 는 필수이며 허용 개인 키 Scope 를 넘지 않습니다." },
  ],
  visit: [
    { key: "visit.early_checkin_minutes", label: "조기 체크인 허용 (분)", type: "number" }, { key: "visit.late_grace_minutes", label: "미방문 판정 유예 (분)", type: "number" }, { key: "visit.dynamic_qr_seconds", label: "Dynamic QR 주기 (초)", type: "number", help: "0은 고정 서버 검증 QR, 권장 Dynamic 값은 30~60" }, { key: "visit.auto_checkout_hour", label: "자동 퇴실 처리 시각", type: "number" }, { key: "visit.approval_escalation_hours", label: "승인 지연 에스컬레이션 (시간)", type: "number", help: "승인 대기가 이 시간을 넘으면 approval_escalated 알림 규칙이 한 번 발송됩니다." }, { key: "visit.self_registration_hours", label: "사전등록 링크 유효기간 (시간)", type: "number" },
  ],
  notification: [
    { key: "notification.provider", label: "기존 Provider", help: "API를 선택하지 않은 규칙의 log 또는 webhook Adapter" }, { key: "notification.webhook_url", label: "기존 Webhook URL" }, { key: "notification.auth_header", label: "기존 Authorization Header", secret: true },
  ],
  mail: [
    { key: "smtp.host", label: "SMTP 서버" }, { key: "smtp.port", label: "포트", type: "number", help: "STARTTLS 587, TLS 465, 평문 25" }, { key: "smtp.security", label: "보안 방식", help: "starttls · tls · none" }, { key: "smtp.from", label: "발신자", help: "예: VisitFlow <visitflow@company.intra>" }, { key: "smtp.username", label: "계정 (선택)" }, { key: "smtp.password", label: "비밀번호", secret: true }, { key: "auth.password_reset_minutes", label: "재설정 링크 유효시간 (분)", type: "number" },
  ],
  privacy: [
    { key: "privacy.mask_after_days", label: "마스킹 전환 (일)", type: "number" }, { key: "privacy.destroy_after_days", label: "개인 식별정보 자동 파기 (일)", type: "number" }, { key: "privacy.audit_retention_days", label: "감사 로그 보존 (일)", type: "number" }, { key: "privacy.consent_policy_version", label: "동의 정책 버전", help: "동의 문구를 바꾸면 버전을 올리세요. 모든 동의 기록에 함께 저장됩니다." },
  ],
  tracking: [
    { key: "tracking.provider", label: "Provider", options: [["none", "없음"], ["momento", "Momento (사내 수집기)"], ["ga4", "Google Analytics 4"], ["gtm", "Google Tag Manager"], ["matomo", "Matomo"], ["custom", "직접 입력"]], help: "Momento는 사내 자체 호스팅 수집기로, 데이터가 밖으로 나가지 않는 유일한 선택지입니다." }, { key: "tracking.placement", label: "삽입 위치", options: [["head", "head"], ["body", "body"]], help: "스니펫을 </head> 앞에 둘지 </body> 앞에 둘지 정합니다." },
    { key: "tracking.momento_url", label: "Momento 수집기 주소", help: "예: https://momento.company.intra. 같은 오리진 프록시를 켜면 브라우저는 이 주소를 직접 부르지 않고 /momento/* 로 접근합니다." }, { key: "tracking.momento_site_id", label: "Momento 사이트 ID" }, { key: "tracking.momento_environment", label: "Momento 환경", help: "data-environment 값. 기본 prd" },
    { key: "tracking.measurement_id", label: "GA4 · GTM ID", help: "GA4는 G-XXXX, GTM은 GTM-XXXX" }, { key: "tracking.matomo_url", label: "Matomo 서버 주소" }, { key: "tracking.matomo_site_id", label: "Matomo 사이트 ID" },
    { key: "tracking.custom_snippet", label: "추적 코드 (직접 입력)", multiline: true, help: "도구가 준 <script> 스니펫을 그대로 붙여 넣습니다. 8KB까지. 모든 <script> 태그에 요청마다 nonce가 붙고, 코드 안의 http(s) 출처는 자동으로 정책에 더해집니다." },
    { key: "tracking.allowed_hosts", label: "추가 허용 출처", multiline: true, help: "스니펫에서 자동으로 읽지 못한 출처를 https://host 형태로 쉼표·줄바꿈으로 구분해 적습니다. 아래 차단 목록의 허용 버튼이 여기에 더합니다." },
  ],
  security: [
    { key: "security.session_hours", label: "세션 유효시간 (시간)", type: "number" }, { key: "security.api_key_days", label: "개인 키 기본 유효기간 (일)", type: "number" }, { key: "security.rotation_grace_hours", label: "키 회전 유예시간 (시간)", type: "number" }, { key: "security.api_key_allowed_scopes", label: "허용 개인 키 Scope", help: "read write mcp 중 허용할 범위를 공백으로 구분합니다. 제거한 Scope는 기존 키에도 즉시 차단됩니다." }, { key: "security.api_key_max_active", label: "사용자별 활성 키 한도", type: "number" }, { key: "security.login_max_attempts", label: "로그인 실패 허용 횟수", type: "number", help: "IP와 계정 각각에 적용됩니다." }, { key: "security.login_lockout_minutes", label: "로그인 잠금 시간 (분)", type: "number" }, { key: "security.public_rate_limit_per_minute", label: "공개 API 분당 요청 한도", type: "number", help: "모바일 방문증, QR 이미지, 사전등록, 로그인에 적용됩니다." }, { key: "security.trusted_proxies", label: "신뢰할 Reverse Proxy", help: "리버스 프록시의 IP·CIDR을 공백으로 구분해 입력하면 X-Forwarded-For의 실제 접속 IP를 잠금·요청 한도·감사 로그에 사용합니다. 사내 대역 전체는 private 한 단어로 지정합니다. 비워두면 헤더를 무시합니다." }, { key: "security.metrics_token", label: "Prometheus /metrics 토큰", secret: true, help: "설정하기 전까지 /metrics 엔드포인트는 404를 반환합니다." },
  ],
};

export function SettingsPage() {
  const [items, setItems] = useState<Setting[]>([]); const [values, setValues] = useState<Record<string, string>>({}); const [tab, setTab] = useState("general"); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState("");
  const load = async () => { try { const data = await api<{ items: Setting[] }>("/api/v1/settings"); setItems(data.items); setValues(Object.fromEntries(data.items.map((x) => [x.key, x.value]))); } catch (e) { setError(e instanceof Error ? e.message : "설정을 불러오지 못했습니다"); } }; useEffect(() => { void load(); }, []);
  const configured = useMemo(() => Object.fromEntries(items.map((x) => [x.key, x.configured])), [items]); const dirty = useMemo(() => items.some((item) => (values[item.key] ?? "") !== item.value), [items, values]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const save = async () => { setSaving(true); setError(""); try { await putJSON("/api/v1/settings", { settings: values }); setMessage("설정을 저장했습니다. 새 요청부터 즉시 적용됩니다."); await load(); return true; } catch (e) { setError(e instanceof Error ? e.message : "저장하지 못했습니다"); return false; } finally { setSaving(false); } };
  const test = async () => { try { if (!(await save())) return; const result = await api<{ redirectUri: string }>("/api/v1/settings/oidc/test", { method: "POST" }); setMessage(`Keycloak Discovery 연결 성공 · Callback ${result.redirectUri}`); } catch (e) { setError(e instanceof Error ? e.message : "연결하지 못했습니다"); } };
  const [smtpTestTo, setSmtpTestTo] = useState(""); const [smtpTesting, setSmtpTesting] = useState(false);
  const testSMTP = async () => { setSmtpTesting(true); setError(""); try { if (dirty && !(await save())) return; const result = await postJSON<{ ok: boolean; durationMs: number; error?: string; enabled: boolean }>("/api/v1/settings/smtp/test", { to: smtpTestTo }); if (result.ok) setMessage(`테스트 메일을 보냈습니다 (${result.durationMs}ms).${result.enabled ? "" : " SMTP 사용 스위치가 꺼져 있어 실제 알림은 발송되지 않습니다."}`); else setError(`테스트 실패: ${result.error ?? "알 수 없는 오류"}`); } catch (e) { setError(e instanceof Error ? e.message : "테스트 메일을 보내지 못했습니다"); } finally { setSmtpTesting(false); } };
  const changePassword = async () => { try { await postJSON("/api/v1/auth/password", { currentPassword, newPassword }); setCurrentPassword(""); setNewPassword(""); setMessage("관리자 비밀번호를 변경하고 다른 세션을 종료했습니다."); } catch (e) { setError(e instanceof Error ? e.message : "비밀번호를 변경하지 못했습니다"); } };
  // Import reuses the ordinary save: the export file is exactly a PUT body.
  const importSettings = async (file?: File) => { if (!file) return; setError(""); try { const parsed = JSON.parse(await file.text()) as { format?: string; settings?: Record<string, string> }; if (parsed.format !== "visitflow-settings/1" || !parsed.settings) throw new Error("VisitFlow 설정 내보내기 파일이 아닙니다"); const known = new Set(items.map((x) => x.key)); const incoming = Object.fromEntries(Object.entries(parsed.settings).filter(([key]) => known.has(key))); setValues((v) => ({ ...v, ...incoming })); setMessage(`${Object.keys(incoming).length}개 설정을 불러왔습니다. 확인 후 저장하세요.`); } catch (e) { setError(e instanceof Error ? e.message : "설정 파일을 읽지 못했습니다"); } };
  const [violations, setViolations] = useState<TrackingViolation[]>([]);
  const loadViolations = async () => { try { const data = await api<{ items: TrackingViolation[] }>("/api/v1/admin/tracking/violations"); setViolations(data.items); } catch { /* the panel is a troubleshooting aid; the settings form still works without it */ } };
  useEffect(() => { if (tab === "tracking") void loadViolations(); }, [tab]);
  // Allowing a blocked origin is the one-click fix for a policy report: the
  // server appends it to tracking.allowed_hosts, so reload the form too.
  const allowOrigin = async (origin: string) => { setError(""); try { await postJSON("/api/v1/admin/tracking/allow", { origin }); setMessage(`${origin} 을(를) 허용 출처에 더했습니다. 새 요청부터 적용됩니다.`); await load(); await loadViolations(); } catch (e) { setError(e instanceof Error ? e.message : "출처를 허용하지 못했습니다"); } };
  const clearViolations = async () => { try { await api("/api/v1/admin/tracking/violations", { method: "DELETE" }); await loadViolations(); } catch (e) { setError(e instanceof Error ? e.message : "차단 기록을 비우지 못했습니다"); } };
  // The identifiers an MCP client needs, derived the way the server derives
  // them: the configured resource, else the public base URL, else this origin.
  const mcpResource = values["mcp.oauth.resource"] || `${(values["general.base_url"] || window.location.origin).replace(/\/+$/, "")}/mcp`;
  const mcpMetadataUrl = `${mcpResource.replace(/\/mcp$/, "")}/.well-known/oauth-protected-resource/mcp`;
  const toggle = (key: string, label: string) => <FormControlLabel control={<Switch checked={values[key] === "true"} onChange={(e) => setValues((v) => ({ ...v, [key]: String(e.target.checked) }))} />} label={label} />;
  return <Box sx={{ p: { xs: 2, md: 3 }, maxWidth: 1150, mx: "auto" }}><PageHeader eyebrow="SYSTEM CONTROL" title="시스템 설정" description="배포 환경변수는 PostgreSQL DSN, Bootstrap 계정 2개와 Encryption Key뿐이며, 나머지 운영 설정은 여기에서 관리합니다." actions={dirty ? <Chip icon={<WarningAmberRounded />} color="warning" label="저장하지 않은 변경" /> : <Chip icon={<CheckCircleRounded />} color="success" variant="outlined" label="모든 변경 저장됨" />} />{message && <Alert severity="success" onClose={() => setMessage("")} sx={{ mb: 2 }}>{message}</Alert>}{error && <Alert severity="error" onClose={() => setError("")} sx={{ mb: 2 }}>{error}</Alert>}
    <Card><Stack direction={{ xs: "column", sm: "row" }} spacing={1} sx={{ px: 2.5, pt: 2 }}><Chip size="small" color={values["oidc.enabled"] === "true" ? "success" : "default"} variant="outlined" label={`Keycloak ${values["oidc.enabled"] === "true" ? "활성" : "비활성"}`} /><Chip size="small" color={values["visit.approval_enabled"] === "true" ? "warning" : "success"} variant="outlined" label={`승인 ${values["visit.approval_enabled"] === "true" ? "Workflow" : "자동 확정"}`} /><Chip size="small" variant="outlined" label={`기존 알림 ${values["notification.provider"] || "log"}`} /></Stack><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable" scrollButtons="auto" sx={{ px: 2, borderBottom: "1px solid #E1E9E6" }}>{[["general", "일반"], ["oidc", "Keycloak SSO"], ["visit", "방문 · QR 정책"], ["notification", "기존 알림 Adapter"], ["mail", "메일 (SMTP)"], ["privacy", "개인정보"], ["tracking", "방문 추적"], ["security", "보안 · 키"]].map(([value, label]) => <Tab key={value} value={value} label={label} />)}</Tabs><CardContent sx={{ p: { xs: 2, md: 4 } }}>
      {tab === "oidc" && <><Stack direction={{ xs: "column", sm: "row" }} spacing={2} mb={3}>{toggle("oidc.enabled", "Keycloak SSO 사용")}{toggle("auth.local_enabled", "로컬 관리자 로그인 허용")}{toggle("oidc.auto_provision", "SSO 사용자 자동 생성")}{toggle("oidc.auto_login", "Keycloak 세션이 있으면 자동 로그인")}</Stack><Alert severity="info" sx={{ mb: 3 }}>Keycloak Client의 Valid Redirect URI에 <strong>{window.location.origin}/api/v1/auth/oidc/callback</strong>을 등록하세요. Issuer, Client ID, Client Secret만으로 Discovery와 PKCE 연결이 자동 구성됩니다. 자동 로그인을 켜면 Keycloak에 이미 로그인한 사용자는 로그인 화면 없이 바로 들어옵니다(탭당 한 번만 시도하며, 로그아웃한 뒤에는 시도하지 않습니다).</Alert>
        <Divider sx={{ mb: 2 }} /><Typography variant="h6">MCP를 Keycloak 토큰으로 열기 (OAuth)</Typography><Stack direction={{ xs: "column", sm: "row" }} spacing={2} mt={1} mb={2}>{toggle("mcp.oauth.enabled", "MCP SSO(OAuth) 인증 사용")}</Stack>
        <Alert severity={values["mcp.oauth.enabled"] === "true" ? "success" : "info"} sx={{ mb: 3 }}>개인 키 없이 MCP 클라이언트에 <strong>URL 하나</strong>만 주면 클라이언트가 스스로 Keycloak 로그인을 띄우고 토큰을 받아 옵니다. 이 서버는 토큰을 검사만 하며(리소스 서버) 계정을 만들지 않습니다 — 웹으로 한 번 로그인한 활성 계정만 들어옵니다. Keycloak에는 웹 로그인과 <strong>다른</strong> 공개(public) 클라이언트를 PKCE S256으로 만들고, 정식 경로는 Audience 매퍼에 리소스 식별자를, 호환 경로는 아래 허용 대상에 클라이언트 ID를 적습니다.
          <Stack spacing={.5} mt={1.5}>{[["MCP URL", mcpResource], ["메타데이터 주소", mcpMetadataUrl]].map(([label, value]) => <Stack key={label} direction="row" spacing={1} alignItems="center"><Typography variant="body2" sx={{ minWidth: 110 }}>{label}</Typography><code style={{ wordBreak: "break-all" }}>{value}</code><Button size="small" startIcon={<ContentCopyRounded />} onClick={() => void navigator.clipboard.writeText(value).catch(() => undefined)}>복사</Button></Stack>)}</Stack></Alert></>}
      {tab === "visit" && <Stack direction={{ xs: "column", sm: "row" }} spacing={2} mb={3}>{toggle("visit.approval_enabled", "방문 승인 Workflow")}{toggle("visit.single_use_qr", "QR 1회 체크인")}{toggle("visit.company_required", "회사명 필수")}{toggle("visit.self_registration_enabled", "방문자 셀프 사전등록")}</Stack>}
      {tab === "mail" && <><Stack direction={{ xs: "column", sm: "row" }} spacing={2} mb={3}>{toggle("smtp.enabled", "SMTP 메일 발송 사용")}{toggle("auth.password_reset_enabled", "로컬 계정 메일 비밀번호 재설정")}{toggle("smtp.skip_tls_verify", "TLS 인증서 검증 생략 (사설 인증서)")}</Stack><Alert severity="info" sx={{ mb: 3 }}>사내 SMTP 릴레이를 연결하면 담당자별 메일 알림(도착·승인·반려·취소·승인 대기)과 Keycloak을 쓰지 않는 로컬 계정의 비밀번호 재설정 메일이 동작합니다. 인증은 STARTTLS/TLS 위에서 PLAIN, 그 외 LOGIN·CRAM-MD5를 자동 선택합니다. 사용자는 프로필 메뉴에서 받을 메일을 직접 고릅니다.</Alert></>}
      {tab === "privacy" && <Alert severity="warning" sx={{ mb: 3 }}>방문 정보는 목록에서 항상 최소 노출되며, 파기일이 지나면 이름·전화·이메일·차량번호를 복구 불가능하게 대체합니다. 감사 통계는 식별정보 없이 유지됩니다.</Alert>}
      {tab === "tracking" && <><Stack direction={{ xs: "column", sm: "row" }} spacing={2} mb={3}>{toggle("tracking.enabled", "방문 추적 사용")}{toggle("tracking.momento_proxy", "Momento 같은 오리진 프록시 (/momento)")}{toggle("tracking.include_admin", "관리 화면(/admin)에서도 추적")}</Stack><Alert severity="info" sx={{ mb: 3 }}>이 앱의 콘텐츠 보안 정책(CSP)은 스크립트를 자기 오리진으로 잠가 두므로 스니펫을 그냥 붙이면 조용히 차단됩니다. 추적을 켜면 페이지마다 새 nonce를 스니펫의 모든 <code>&lt;script&gt;</code>에 달아 <code>script-src</code>에 넣고, 스니펫 안의 http(s) 출처를 <code>script-src · connect-src · img-src</code>에 더하며, 그래도 차단된 요청은 브라우저가 신고해 아래 표에 나타납니다. 정책을 <code>'unsafe-inline'</code>으로 푸는 일은 없으며 추적을 끄면 정책은 원래대로 좁아집니다. Momento 프록시를 켜면 외부 출처가 정책에 아예 등장하지 않습니다. 로그인·방문증·사전등록·키오스크 화면에도 스니펫이 들어가므로 개인 식별 값을 보내는 코드는 넣지 마세요.</Alert></>}
      {tab === "notification" && <Alert severity="info" sx={{ mb: 3 }} action={<Button color="inherit" size="small" href="/admin/notification-settings">API·규칙 관리</Button>}><strong>log/webhook</strong>은 API를 선택하지 않은 규칙의 호환 Adapter입니다. SMS·MMS·카카오톡 URL, path, parameter, 템플릿과 발송 시점은 전용 화면에서 관리합니다.</Alert>}
      <Grid container spacing={2.5}>{fields[tab].map((f) => <Grid key={f.key} size={{ xs: 12, md: f.multiline ? 12 : 6 }}><TextField fullWidth select={Boolean(f.options)} multiline={f.multiline} minRows={f.multiline ? 3 : undefined} label={f.label} type={f.secret ? "password" : f.type || "text"} value={values[f.key] ?? ""} onChange={(e) => setValues((v) => ({ ...v, [f.key]: e.target.value }))} helperText={f.help || (f.secret && configured[f.key] ? "AES-256-GCM으로 암호화되어 있습니다. 변경할 때만 새 값을 입력하세요." : " ")}>{f.options?.map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></Grid>)}</Grid>
      {tab === "tracking" && <Box sx={{ mt: 3 }}><Divider sx={{ mb: 3 }} /><Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 1 }}><Typography variant="h6">정책이 차단한 출처</Typography><Stack direction="row" spacing={1}><Button size="small" onClick={() => void loadViolations()}>새로고침</Button><Button size="small" color="warning" disabled={violations.length === 0} onClick={() => void clearViolations()}>기록 비우기</Button></Stack></Stack><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>추적이 켜진 동안 브라우저가 신고한 차단 요청입니다. 메모리에 최근 100개 출처만 두므로 재시작하면 비워집니다. 허용을 누르면 추가 허용 출처에 들어가고, 이미 정책에 있는 출처는 허용됨으로 표시됩니다.</Typography>{violations.length === 0 ? <Typography variant="body2" color="text.secondary">신고된 차단이 없습니다.</Typography> : <Table size="small"><TableHead><TableRow><TableCell>출처</TableCell><TableCell>지시어</TableCell><TableCell>횟수</TableCell><TableCell>마지막 페이지</TableCell><TableCell>마지막 신고</TableCell><TableCell align="right">허용</TableCell></TableRow></TableHead><TableBody>{violations.map((v) => <TableRow key={`${v.directive} ${v.origin}`}><TableCell><code>{v.origin}</code></TableCell><TableCell>{v.directive}</TableCell><TableCell>{v.count}</TableCell><TableCell sx={{ maxWidth: 260, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{v.page}</TableCell><TableCell>{new Date(v.lastSeen).toLocaleString()}</TableCell><TableCell align="right">{v.allowed ? <Chip size="small" color="success" variant="outlined" label="허용됨" /> : <Button size="small" variant="outlined" onClick={() => void allowOrigin(v.origin)}>허용 목록에 추가</Button>}</TableCell></TableRow>)}</TableBody></Table>}</Box>}
      {tab === "mail" && <Box sx={{ mt: 3 }}><Divider sx={{ mb: 3 }} /><Typography variant="h6">테스트 메일</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>저장된 설정으로 실제 메일을 한 통 보냅니다. 저장하지 않은 변경이 있으면 먼저 저장합니다.</Typography><Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField type="email" label="수신 이메일" value={smtpTestTo} onChange={(e) => setSmtpTestTo(e.target.value)} sx={{ minWidth: 280 }} /><Button variant="outlined" disabled={!smtpTestTo || smtpTesting} onClick={() => void testSMTP()}>{smtpTesting ? "발송 중…" : "테스트 메일 발송"}</Button></Stack></Box>}
      {tab === "security" && <Box sx={{ mt: 3 }}><Alert severity="warning" sx={{ mb: 3 }}><strong>ENCRYPTION_KEY</strong>는 설정 화면에서 변경하지 않습니다. PostgreSQL 백업과 함께 안전하게 보관하고, 모든 노드에 동일한 32바이트 키를 주입하세요. 키가 달라지면 암호화된 개인정보와 Client Secret을 복호화할 수 없습니다.</Alert><Divider sx={{ mb: 3 }} /><Typography variant="h6">내 로컬 관리자 비밀번호</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>SSO 사용자는 Keycloak에서 변경합니다.</Typography><Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField type="password" label="현재 비밀번호" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /><TextField type="password" label="새 비밀번호 (12자 이상)" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /><Button variant="outlined" disabled={!currentPassword || newPassword.length < 12} onClick={() => void changePassword()}>비밀번호 변경</Button></Stack></Box>}
      <Divider sx={{ my: 3 }} /><Stack direction={{ xs: "column-reverse", sm: "row" }} justifyContent="flex-end" spacing={1}><Button href="/api/v1/settings/export" download>설정 내보내기</Button><Button component="label">설정 가져오기<input hidden type="file" accept="application/json,.json" onChange={(e) => { void importSettings(e.target.files?.[0]); e.currentTarget.value = ""; }} /></Button>{tab === "oidc" && <Button startIcon={<LinkRounded />} onClick={() => void test()}>저장 후 연결 테스트</Button>}<Button variant="contained" startIcon={<SaveRounded />} disabled={!dirty || saving} onClick={() => void save()}>{saving ? "저장 중…" : "설정 저장"}</Button></Stack>
    </CardContent></Card><Stack direction="row" spacing={1} mt={2} flexWrap="wrap"><Chip label="비밀값 AES-256-GCM" variant="outlined" /><Chip label="변경 Before/After 감사 대상" variant="outlined" /><Chip label="런타임 CDN 0개" variant="outlined" /></Stack>
  </Box>;
}
